### PR TITLE
No owned void

### LINKED ISSUE #568: [CN] crash if a resource is required on a void pointer
Not much to it. Should give an error with source location instead.

```
int f(void *e)
/*@
  requires take ei = Owned(e);
  @*/
{       }
```
```
cn verify  cn_crash_1.c
internal error: size_of_ctype applied to void
cn: internal error, uncaught exception:
    Failure("internal error: size_of_ctype applied to void")
```

### PR DESCRIPTION
**Pull request by cp526**
fix https://github.com/rems-project/cerberus/issues/568

### CODE REVIEW

File: backend/cn/lib/wellTyped.ml [hunk 1]
```diff
@@ -1053,6 +1053,25 @@ let warn_when_not_quantifier_bt
...
+  in
+  match ct with
+  | Void ->
+    let msg =
+      pp_resource "void"
+      ^^^ !^"is not a valid resource,"
+      ^^^ !^"please specify another C-type"
+      ^^^ Pp.parens (!^"using" ^^^ pp_resource "YOURTYPE")
+    in
+    fail { loc; msg = Generic msg }
```
Comment (dc-mak) [inline backend/cn/lib/wellTyped.ml:1071]: Please add specific constructors instead of using Generic

**Comment by dc-mak** [comment]
Does this fix #851?

**Comment by cp526** [comment]
> Does this fix #851?

No:

```
cerberus > cn verify ~/Desktop/test.c
/Users/christopher/Desktop/test.c:30:7: warning: experimental keyword 'to_bytes' (use of experimental features is discouraged)
  /*@ to_bytes Owned<s>(p); @*/
      ^~~~~~~~
cn: internal error, uncaught exception:
    File "backend/cn/lib/check.ml", line 1867, characters 74-80: Assertion failed
    Raised at Cn__Check.check_expr.bytes_constraints in file "backend/cn/lib/check.ml", line 1867, characters 74-86
    Called from Cn__Check.check_expr.aux in file "backend/cn/lib/check.ml", line 1924, characters 38-77
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.pure.(fun) in file "backend/cn/lib/typing.ml", line 76, characters 22-25
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.pure.(fun) in file "backend/cn/lib/typing.ml", line 76, characters 22-25
    Called from Cn__Typing.sandbox.(fun) in file "backend/cn/lib/typing.ml", line 86, characters 10-13
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.bind.(fun) in file "backend/cn/lib/typing.ml", line 49, characters 17-20
    Called from Cn__Typing.run_from_pause in file "backend/cn/lib/typing.ml", line 68, characters 50-55
    Called from Dune__exe__Main.with_well_formedness_check in file "backend/cn/bin/main.ml", line 176, characters 15-69
    Called from Dune__exe__Main.with_well_formedness_check in file "backend/cn/bin/main.ml", lines 165-186, characters 6-15
    Re-raised at Dune__exe__Main.with_well_formedness_check in file "backend/cn/bin/main.ml", line 194, characters 4-69
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
```
